#!/bin/bash
echo "Run these commands to get your Vercel project info:"
echo ""
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Login: vercel login"
echo "3. Link project: vercel link"
echo "4. Get project info: vercel project ls"
echo ""
echo "Then add these as GitHub repository secrets:"
echo "- VERCEL_TOKEN (from Vercel dashboard)"
echo "- ORG_ID (from vercel project ls output)"
echo "- PROJECT_ID (from vercel project ls output)"
